### ISSUE TITLE
Change Context Menu ?

### ISSUE THREAD

**Issue by SheepDomination** [Denisov21/Popup-menu-extension#11]
Can I add whatever I want to the "convert-to" context menu & can it be renamed from "convert-to" to something else ?

**Comment by Denisov21** [comment]
Yes, of course!

**Comment by SheepDomination** [comment]
How ;-) ?

**Comment by Denisov21** [comment]
what language you use brackets?

**Comment by SheepDomination** [comment]
English !

**Comment by Denisov21** [comment]
1. Go in 
   C:\Users\xxxx\AppData\Roaming\Brackets\extensions\user\denisov21.pop-up-menu extension\nls\root
2. open file strings.js 
3. you find a string call "convert to" change with anything
4. save
5. Reboot Brackets

**Comment by SheepDomination** [comment]
Hi, that worked, how can I add to the menu ?

Denis R wrote:
