### ISSUE TITLE
Undo menu

### ISSUE THREAD

**Issue by atgr24869** [Denisov21/Popup-menu-extension#18]
Hi, is it possible to add an "Undo" menu item?
Thanks.

**Comment by Denisov21** [comment]
Hi @harrison3001,
Yes, of course!

**Comment by Denisov21** [comment]
Done!

**Comment by atgr24869** [comment]
Many, many, many Thanks!!! :)

**Comment by atgr24869** [comment]
Fantastic, again, Best Wishes!!!

**Comment by Denisov21** [comment]
Prego, mi fa piacere che ti piaccia!
